name: docker-development-setup
services:
  devcontainer:
    container_name: devcontainer
    hostname: devcontainer
    build:
      context: devcontainer/
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-available/php:/etc/nginx/sites-enabled/php
      - ./nginx/sites-available/sf:/etc/nginx/sites-enabled/sf
      - ./nginx/sites-available/ez:/etc/nginx/sites-enabled/ez
      - ./nginx/sites-available/node:/etc/nginx/sites-enabled/node
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./websites/:/private/var/www/
      - ./devcontainer/supervisord.conf:/etc/supervisor/supervisord.conf:ro
      - ./ssl/:/etc/nginx/ssl/
      - ./ssl/root.crt:/usr/local/share/ca-certificates/root.crt
      - ~/nvm-node/:/root/.nvm/versions/node/
      - ~/.ssh/id_rsa:/root/.ssh/id_rsa
      - ~/.ssh/known_hosts:/root/.ssh/known_hosts
      - ~/.config/composer/:/root/.config/composer/
      - ./shell/aliases.sh:/root/.bash_aliases
      - ~/.git-credentials:/root/.git-credentials
    command:
      - /usr/local/bin/supervisord
    restart: unless-stopped
    networks:
      - mysql-network
      - redis-network
      - solr-network
      - mailpit-network

  mysql:
    container_name: mysql
    image: mysql:8.0.40
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
    restart: unless-stopped
    networks:
      - mysql-network
    ports:
      - 3306:3306

  solr:
    container_name: solr
    image: solr:8.11.4
    restart: unless-stopped
    volumes:
      - solr-data:/var/solr
    networks:
      - solr-network
    ports:
      - 8983:8983

  redis:
    image: redis:7.0.9-alpine3.17
    container_name: redis
    restart: unless-stopped
    networks:
      - redis-network

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: unless-stopped
    networks:
      - mailpit-network
    ports:
      - 8025:8025

networks:
  mysql-network:
  redis-network:
  solr-network:
  mailpit-network:

volumes:
  mysql-data:
    name: mysql-data
  solr-data:
    name: solr-data
