[req]
prompt=no
string_mask=default
default_bits=2048
distinguished_name=req_distinguished_name
x509_extensions=x509_ext

[req_distinguished_name]
countryName=hr
organizationName=Local
commonName=Local Development

[x509_ext]
keyUsage=critical,digitalSignature,keyAgreement
subjectAltName=@alt_names

[alt_names]
DNS.1=home.php94
DNS.2=home.php93
DNS.3=home.php92
DNS.4=home.php91
DNS.5=home.php90
DNS.6=home.php85
DNS.7=home.php84
DNS.8=home.php83
DNS.9=home.php82
DNS.10=home.php81
DNS.11=home.php80
DNS.12=home.php74
DNS.13=phpinfo.php94
DNS.14=phpinfo.php93
DNS.15=phpinfo.php92
DNS.16=phpinfo.php91
DNS.17=phpinfo.php90
DNS.18=phpinfo.php85
DNS.19=phpinfo.php84
DNS.20=phpinfo.php83
DNS.21=phpinfo.php82
DNS.22=phpinfo.php81
DNS.23=phpinfo.php80
DNS.24=phpinfo.php74
DNS.25=*.dev.php94.ez
DNS.26=*.dev.php93.ez
DNS.27=*.dev.php92.ez
DNS.28=*.dev.php91.ez
DNS.29=*.dev.php90.ez
DNS.30=*.dev.php85.ez
DNS.31=*.dev.php84.ez
DNS.32=*.dev.php83.ez
DNS.33=*.dev.php82.ez
DNS.34=*.dev.php81.ez
DNS.35=*.dev.php80.ez
DNS.36=*.dev.php74.ez
DNS.37=*.prod.php94.ez
DNS.38=*.prod.php93.ez
DNS.39=*.prod.php92.ez
DNS.40=*.prod.php91.ez
DNS.41=*.prod.php90.ez
DNS.42=*.prod.php85.ez
DNS.43=*.prod.php84.ez
DNS.44=*.prod.php83.ez
DNS.45=*.prod.php82.ez
DNS.46=*.prod.php81.ez
DNS.47=*.prod.php80.ez
DNS.48=*.prod.php74.ez
DNS.49=*.test.php94.ez
DNS.50=*.test.php93.ez
DNS.51=*.test.php92.ez
DNS.52=*.test.php91.ez
DNS.53=*.test.php90.ez
DNS.54=*.test.php85.ez
DNS.55=*.test.php84.ez
DNS.56=*.test.php83.ez
DNS.57=*.test.php82.ez
DNS.58=*.test.php81.ez
DNS.59=*.test.php80.ez
DNS.60=*.test.php74.ez
DNS.61=*.dev.php94.sf
DNS.62=*.dev.php93.sf
DNS.63=*.dev.php92.sf
DNS.64=*.dev.php91.sf
DNS.65=*.dev.php90.sf
DNS.66=*.dev.php85.sf
DNS.67=*.dev.php84.sf
DNS.68=*.dev.php83.sf
DNS.69=*.dev.php82.sf
DNS.70=*.dev.php81.sf
DNS.71=*.dev.php80.sf
DNS.72=*.dev.php74.sf
DNS.73=*.prod.php94.sf
DNS.74=*.prod.php93.sf
DNS.75=*.prod.php92.sf
DNS.76=*.prod.php91.sf
DNS.77=*.prod.php90.sf
DNS.78=*.prod.php85.sf
DNS.79=*.prod.php84.sf
DNS.80=*.prod.php83.sf
DNS.81=*.prod.php82.sf
DNS.82=*.prod.php81.sf
DNS.83=*.prod.php80.sf
DNS.84=*.prod.php74.sf
DNS.85=*.test.php94.sf
DNS.86=*.test.php93.sf
DNS.87=*.test.php92.sf
DNS.88=*.test.php91.sf
DNS.89=*.test.php90.sf
DNS.90=*.test.php85.sf
DNS.91=*.test.php84.sf
DNS.92=*.test.php83.sf
DNS.93=*.test.php82.sf
DNS.94=*.test.php81.sf
DNS.95=*.test.php80.sf
DNS.96=*.test.php74.sf
DNS.97=*.node
